development:
  adapter: postgresql
  encoding: unicode
  database: medialog-dev
  username: medialog
  password: medialog
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: medialog-test
  username: medialog
  password: medialog
  host: localhost
  port: 5432