development:
  adapter: postgresql
  encoding: unicode
  database: medialogdev
  username: medialog
  password: medialog
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: medialogtest
  username: medialog
  password: medialog
  host: localhost
  port: 5432